name: boilerplate calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # ... (previous steps)

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Debugging step to show Docker info
    - name: Debugging - Show Docker Info
      run: docker info

    - name: Pull Docker Image from Docker Hub
      run: docker pull eliekhoury1/prob_calculator:594863361c25d859ac193c2b4906babacb03f235
